backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "dharma"
    label: "Dharma Section"
    folder: "content/dharma"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
