backend:
  name: github
  repo: your-github-username/ONE-Channel-Book
  branch: main

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "dharma"
    label: "Dharma Section"
    folder: "content/dharma"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "baydin"
    label: "Baydin Section"
    folder: "content/baydin"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "health"
    label: "Health Section"
    folder: "content/health"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}

  - name: "jataka"
    label: "Jataka Section"
    folder: "content/jataka"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}